export type {
  AnnouncementStatus,
  ConsultationRequestStatus,
  ConsultationStatus,
  DemoAnnouncement,
  DemoConsultation,
  DemoConsultationRequest,
  DemoPatient,
  DemoReportRow,
  DemoSettingsSection,
  DemoStaffUser,
  DemoStat,
  StaffAccountStatus,
} from "@/lib/demo/types"

export {
  demoAnnouncementStats,
  demoAnnouncements,
  demoConsultationRequests,
  demoConsultationStats,
  demoConsultations,
  demoPatientStats,
  demoPatients,
  demoReportRows,
  demoReportStats,
  demoRequestStats,
  demoSettingsSections,
  demoStaffUsers,
  demoUserStats,
} from "@/lib/demo/fixtures"
